print("Random Person:hello")
you=input("you:")
print("Random Person:What's you'r name?")
you=input("you:")
print("Random person:How old are you?")
you=input("you:")
print("Random Person:Nice to meet you,i am 14 and my name is Niko,Where do you live?")
you=input("you:")
print("Niko:Ohh,i live in Tbilisi,Wanna be friends?")
you=input("you:")
print("Niko:Cool actually what is you hobby?")
you=input("you:")
print("Niko:I like acting, what is your favorite car?")
you=input("you:")
print("Niko:Cool i like it too but i prefer muscle cars like dodge or mustang, do you like dodge and mustang?")
you=input("you:")
print("Niko:Ok now i have to go i hope we will meet again byeee")
you=input("you:")